included:
  - TranslateVideoSubtitles
  - VideoSubtitlesLib

excluded:
  - "**/BuildTools"
  - "**/.build"
  - "**/*.generated.swift"

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - fatal_error_message
  - first_where
  - missing_docs
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing

disabled_rules:
  - trailing_whitespace
  - trailing_comma
  - todo
  - identifier_name
  - function_body_length
  - type_name
  - file_length
  - cyclomatic_complexity
